version: '3'

services:
  db:
    build: docker/mariadb
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: mc
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: mc
    networks:
      backend:
        aliases:
          - db

networks:
  backend:

volumes:
  db_data:
